### ISSUE TITLE
error running locally

### ISSUE THREAD

**Issue by amueller** [openml/openml.org#2]
I tried running the website locally and got
```
0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v7.6.0
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'debug' ]
7 info using npm@6.4.1
8 info using node@v7.6.0
9 verbose run-script [ 'predebug', 'debug', 'postdebug' ]
10 info lifecycle reacttest2@1.0.0~predebug: reacttest2@1.0.0
11 info lifecycle reacttest2@1.0.0~debug: reacttest2@1.0.0
12 verbose lifecycle reacttest2@1.0.0~debug: unsafe-perm in lifecycle true
13 verbose lifecycle reacttest2@1.0.0~debug: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/andy/checkout/website-1/node_modules/.bin:/home/andy/anaconda3/envs/py37/bin:/home/andy/gems/bin:/home/andy/.npm-global/bin:/home/andy/.gem/ruby/2.3.0/bin:/home/andy/.local/bin:/home/andy/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
14 verbose lifecycle reacttest2@1.0.0~debug: CWD: /home/andy/checkout/website-1
15 silly lifecycle reacttest2@1.0.0~debug: Args: [ '-c', 'webpack -d' ]
16 silly lifecycle reacttest2@1.0.0~debug: Returned: code: 1  signal: null
17 info lifecycle reacttest2@1.0.0~debug: Failed to exec debug script
18 verbose stack Error: reacttest2@1.0.0 debug: `webpack -d`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:192:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:192:7)
18 verbose stack     at maybeClose (internal/child_process.js:890:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid reacttest2@1.0.0
20 verbose cwd /home/andy/checkout/website-1
21 verbose Linux 4.15.0-36-generic
22 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "debug"
23 verbose node v7.6.0
24 verbose npm  v6.4.1
25 error code ELIFECYCLE
26 error errno 1
27 error reacttest2@1.0.0 debug: `webpack -d`
27 error Exit status 1
28 error Failed at the reacttest2@1.0.0 debug script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, tru
```
any idea what the issue is?

**Comment by joaquinvanschoren** [comment]
Which OS are you on? It's probably good to update node and npm.

While testing this I ran into another issue, so I updated the instructions:
https://github.com/openml/openml.org/blob/master/README.md

Please check if this now works for you. Thanks!

**Comment by amueller** [comment]
run the commands in the readme, got
```
ERROR in ./src/client/app/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (/home/andy/checkout/website-1/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/andy/checkout/website-1/node_modules/babel-loader/lib/index.js:3:13)
    at Module._compile (/home/andy/checkout/website-1/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/home/andy/checkout/website-1/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at loadLoader (/home/andy/checkout/website-1/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/home/andy/checkout/website-1/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/andy/checkout/website-1/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/home/andy/checkout/website-1/node_modules/webpack/lib/NormalModule.js:265:3)
    at NormalModule.build (/home/andy/checkout/website-1/node_modules/webpack/lib/NormalModule.js:412:15)
    at Compilation.buildModule (/home/andy/checkout/website-1/node_modules/webpack/lib/Compilation.js:619:10)
    at moduleFactory.create (/home/andy/checkout/website-1/node_modules/webpack/lib/Compilation.js:997:12)
    at factory (/home/andy/checkout/website-1/node_modules/webpack/lib/NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (/home/andy/checkout/website-1/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/andy/checkout/website-1/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/home/andy/checkout/website-1/node_modules/tapable/lib/Hook.js:154:20)
    at resolver (/home/andy/checkout/website-1/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
    at process.nextTick (/home/andy/checkout/website-1/node_modules/webpack/lib/NormalModuleFactory.js:342:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```

**Comment by joaquinvanschoren** [comment]
Weird. What if you do

`npm install babel-core`

and then

`npm run debug`

again?

**Comment by amueller** [comment]
hm might have been a node issue - I upgraded (again?).
Now it seems to run.
But I get
```
> npm run debug



> reacttest2@1.0.0 debug /home/andy/checkout/website-1
> webpack -d

Hash: f2c1b6bb6af90adc605b
Version: webpack 4.21.0
Time: 1655ms
Built at: 10/18/2018 12:08:50 PM
    Asset     Size  Chunks             Chunk Names
bundle.js  2.9 MiB    main  [emitted]  main
Entrypoint main = bundle.js
[./src/client/app/api.js] 7.08 KiB {main} [built]
[./src/client/app/dataset.jsx] 4.4 KiB {main} [built]
[./src/client/app/filterBar.jsx] 10.3 KiB {main} [built]
[./src/client/app/flow.jsx] 4.34 KiB {main} [built]
[./src/client/app/index.jsx] 3.97 KiB {main} [built]
[./src/client/app/itemDetail.jsx] 10.8 KiB {main} [built]
[./src/client/app/login.jsx] 3.26 KiB {main} [built]
[./src/client/app/register.jsx] 7.04 KiB {main} [built]
[./src/client/app/run.jsx] 4.7 KiB {main} [built]
[./src/client/app/search.jsx] 13 KiB {main} [built]
[./src/client/app/sidebar.jsx] 2.38 KiB {main} [built]
[./src/client/app/sizeLimiter.jsx] 1.49 KiB {main} [built]
[./src/client/app/task.jsx] 2.6 KiB {main} [built]
[./src/client/app/topbar.jsx] 837 bytes {main} [built]
[./src/client/app/user.jsx] 12.1 KiB {main} [built]
    + 159 hidden modules
```
and then it exits?

**Comment by joaquinvanschoren** [comment]
Closing since we have new installation instructions: 
https://docs.openml.org/Website/
